### ISSUE TITLE
Boards.txt in the wrong directory ?

### ISSUE THREAD

**Issue by StormRoboticsUK** [oshlab/Breadboard-Arduino#1]
Hi,
I had to move the boards.txt and associated files to sit here: C:\Users\Andy\AppData\Local\Arduino15\packages\Breadboard Arduino\hardware*_avr_*\1.6.9

Rather than here: C:\Users\Andy\AppData\Local\Arduino15\packages\Breadboard Arduino\hardware\avr\1.6.9\avr***

For the file to be picked up OK and recognised.

**Comment by jaretburkett** [comment]
How did you get the board files? Did you use the Boards manager?

**Comment by kenci** [comment]
Here the same. Installed using Boards Manager.

**Comment by jaretburkett** [comment]
It took some tinkering, but I got it working. The way Arduino does the boards manager is a pain in the but. If you use the boards manager to upgrade to the latest package, it should work properly now. For some reason, the files for the boards manager have to be in a completely different folder structure than they need to be for adding hardware manually through the documents path. This makes no sense to me and adds a lot of extra steps to get it to work, but oh well. It should work now.
